apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-frontend
  namespace: ecommerce
  labels:
    app: local-frontend
spec:
  selector:
    matchLabels:
      app: local-frontend
  template:
    metadata:
      labels:
        app: local-frontend
    spec:
      containers:
        - name: local-frontend
          image: frontend-local:ecommerce
          imagePullPolicy: IfNotPresent
          workingDir: /usr/src/app
          command:
            - "/bin/sh"
            - "-c"
          args:
            - "yarn && yarn start"
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - mountPath: /usr/src/app
              name: local-react
      volumes:
        - name: local-react
          hostPath:
            path:  /run/desktop/mnt/host/wsl/ecommerce-mern
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: local-frontend
  namespace: ecommerce
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: local-frontend
  type: NodePort