apiVersion: v1
kind: Secret
metadata:
  name: ecommerce
  namespace: ecommerce
data:
  MONGO_URI: mongodb://database:27017/ecommerce?directConnection=true | base64 
  JWT_SECRET: 123456 | base64  