apiVersion: v1
kind: Secret
metadata:
  name: ecommerce
  namespace: ecommerce
data:
  MONGO_URI: echo -n "mongodb://database:27017/ecommerce?directConnection=true" | base64 
  JWT_SECRET: echo -n "123456" | base64  